"""
 Python Warpper around BASS
 All the constants from Bass.h
"""

BASS_DEVICE_ENABLED = 1
BASS_DEVICE_DEFAULT = 2
BASS_DEVICE_INIT = 4

BASS_DEVICE_8BITS = 1
BASS_DEVICE_MONO = 2
BASS_DEVICE_3D = 4
BASS_DEVICE_LATENCY = 256
BASS_DEVICE_CPSPEAKERS = 1024
BASS_DEVICE_SPEAKERS = 2048
BASS_DEVICE_NOSPEAKER = 4096
BASS_DEVICE_DMIX = 8192 #Linux only

BASS_POS_BYTE = 0

BASS_ACTIVE_STOPPED	= 0
BASS_ACTIVE_PLAYING	= 1
BASS_ACTIVE_STALLED	= 2
BASS_ACTIVE_PAUSED = 3